volumes:
  frijoles-volume:


services:
  frontend:
    build:
      context: ./../Basic3Tier.UI/
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "80:8080"

  backend:
    build:
      context: ./../Basic3Tier.API/
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "8000:80"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=basic3tier
    volumes:
      - frijoles-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
