apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend-deployment
  namespace: finalproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers: 
      - image: kaputinho/basic3tier-front-k8s:latest
        name: frontend
        ports:
          - containerPort: 8080
            name: frontend
    