apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: finalproject
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009
  type: NodePort