apiVersion: v1
kind: Service
metadata:
  labels: 
    app: backend
  name: backend-service
  namespace: finalproject
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
