apiVersion: v1
kind: Service
metadata:
  labels: 
    app: frontend
  name: frontend-service
  namespace: finalproject
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
