apiVersion: v1
kind: Service
metadata:
  labels: 
    app: frontend
  name: frontend-service-nodeport
  namespace: finalproject
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008