apiVersion: v1
kind: Service
metadata:
  name: frontend-service-clusterip
  namespace: finalproject
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
